# Generated by Django 3.0.3 on 2020-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bildirim',
            fields=[
                ('bildirim_id', models.AutoField(primary_key=True, serialize=False)),
                ('bildirim_icerik', models.CharField(max_length=500, null=True)),
                ('bildirim_durum', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
