# Generated by Django 3.0.3 on 2020-04-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bildirim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='bildirim_subs_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
