# Generated by Django 3.0.3 on 2020-04-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='authority',
            field=models.CharField(choices=[('main_dealer', 'Ana Bayi'), ('normal_dealer', 'Normal Bayi'), ('suppliers', 'Tedarikçi'), ('main_dealer_employee', 'Ana Bayi Çalışanı')], max_length=40, verbose_name='Yetki:'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Telefon No:'),
        ),
    ]
