# Generated by Django 3.0.3 on 2020-04-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0002_auto_20200405_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(max_length=30, null=True, verbose_name='Durum:'),
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='status',
            field=models.CharField(max_length=30, null=True, verbose_name='Durum:'),
        ),
    ]
