# Generated by Django 3.0.3 on 2020-04-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0003_auto_20200411_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_kadi',
            field=models.CharField(default='yok', max_length=50, verbose_name='Kullanıcı Adı:'),
        ),
    ]
