# Generated by Django 3.0.3 on 2020-04-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0004_seller_seller_kadi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_kadi',
            field=models.CharField(max_length=50, verbose_name='Kullanıcı Adı:'),
        ),
    ]
