# Generated by Django 3.0.3 on 2020-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_device',
            fields=[
                ('device_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('device_type', models.CharField(choices=[('ws', 'Hava Sensörü'), ('ss', 'Toprak Sensörü'), ('ps', 'Basınç Sensörü'), ('wc', 'Kuyu merkezi')], max_length=2)),
                ('parent_or_child', models.BooleanField()),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory_gsm',
            fields=[
                ('gsm_number', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('gsm_brand', models.CharField(max_length=20)),
                ('date_of_entry_ınv', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
