# Generated by Django 3.0.3 on 2020-04-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0004_auto_20200407_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_device',
            name='seller_id',
            field=models.CharField(max_length=11, null=True, verbose_name='Satıcı ID'),
        ),
    ]
