# Generated by Django 3.0.3 on 2020-04-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0005_inventory_device_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_device',
            name='gsm_brand',
            field=models.CharField(blank=True, choices=[('', '---------'), ('turkcell', 'Turkcell'), ('vodafone', 'Vodafone'), ('turktelekom', 'Türk Telekom')], default=('', '---------'), max_length=20, null=True, verbose_name='Gsm Markası:'),
        ),
    ]
