# Generated by Django 3.0.3 on 2020-04-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0007_inventory_device_subscriber_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_device',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
