# Generated by Django 3.0.3 on 2020-04-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0008_inventory_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_device',
            name='device_type',
            field=models.CharField(choices=[('ws', 'Hava Sensörü'), ('ss', 'Toprak Sensörü'), ('ps', 'Basınç Sensörü'), ('gsm', 'Sim Kart'), ('wc', 'Kuyu merkezi')], max_length=20, verbose_name='Cihaz Tipi:'),
        ),
    ]
