# Generated by Django 3.0.3 on 2020-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0009_auto_20200411_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_id', models.CharField(max_length=700, null=True)),
            ],
        ),
    ]
