# Generated by Django 3.0.3 on 2020-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0010_paket'),
    ]

    operations = [
        migrations.CreateModel(
            name='paketkural',
            fields=[
                ('paket_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('paket_ad', models.CharField(max_length=100)),
                ('paket_kural', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='sellpaket',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(max_length=11, null=True, verbose_name='Satıcı ID')),
                ('subscriber_id', models.CharField(max_length=11, null=True)),
                ('topraks', models.CharField(max_length=100)),
                ('havas', models.CharField(max_length=100)),
                ('basıncs', models.CharField(max_length=100)),
                ('kuyukontrol', models.CharField(max_length=100)),
                ('simkart', models.CharField(max_length=100)),
                ('lisans', models.IntegerField()),
                ('yazlisans', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='paket',
        ),
    ]
