# Generated by Django 3.0.3 on 2020-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0012_remove_sellpaket_lisans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketkural',
            name='paket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
