# Generated by Django 3.0.3 on 2020-04-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberCreate',
            fields=[
                ('subscriber_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('public_ID', models.CharField(max_length=11, unique=True, verbose_name='Tc Kimlik No:')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Telefon No:')),
                ('email_address', models.EmailField(max_length=40, unique=True, verbose_name='E-Posta:')),
                ('first_name', models.CharField(max_length=15, verbose_name='Ad:')),
                ('last_name', models.CharField(max_length=20, verbose_name='Soyad:')),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberAddressCreate',
            fields=[
                ('address_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abone.SubscriberCreate')),
                ('country', models.CharField(default='turkey', max_length=30, verbose_name='Ülke:')),
                ('city', models.CharField(choices=[('1', 'ADANA'), ('2', 'ADIYAMAN'), ('3', 'AFYONKARAHİSAR'), ('4', 'AĞRI'), ('amasya', 'AMASYA'), ('6', 'ANKARA'), ('7', 'ANTALYA'), ('8', 'ARTVİN'), ('9', 'AYDIN'), ('10', 'BALIKESİR'), ('11', 'BİLECİKK'), ('12', 'BİNGÖL'), ('13', 'BİTLİS'), ('14', 'BOLU'), ('15', 'BURDUR'), ('16', 'BURSA'), ('17', 'ÇANAKKALE'), ('18', 'ÇANKIRI'), ('19', 'ÇORUM'), ('20', 'DENİZLİ'), ('21', 'DİYARBAKIR'), ('22', 'EDİRNE'), ('23', 'ELAZIĞ'), ('24', 'ERZİNCAN'), ('25', 'ERZURUM'), ('26', 'ESKİŞEHİR'), ('27', 'GAZİANTEP'), ('28', 'GİRESUN'), ('29', 'GÜMÜŞHANE'), ('30', 'HAKKARİ'), ('31', 'HATAY'), ('32', 'ISPARTA'), ('33', 'MERSİN'), ('34', 'İSTANBUL'), ('35', 'İZMİR'), ('36', 'KARS'), ('37', 'KASTAMONU'), ('38', 'KAYSERİ'), ('39', 'KIRKLARELİ'), ('40', 'KIRŞEHİR'), ('41', 'KOCAELİ'), ('42', 'KONYA'), ('43', 'KÜTAHYA'), ('44', 'MALATYA'), ('45', 'MANİSA'), ('46', 'KAHRAMANMARAŞ'), ('47', 'MARDİN'), ('48', 'MUĞLA'), ('49', 'MUŞ'), ('50', 'NEVŞEHİR'), ('51', 'NİĞDE'), ('52', 'ORDU'), ('53', 'RİZE'), ('54', 'SAKARYA'), ('55', 'SAMSUN'), ('56', 'SİİRT'), ('57', 'SİNOP'), ('58', 'SİVAS'), ('59', 'TEKİRDAĞ'), ('60', 'TOKAT'), ('61', 'TRABZON'), ('62', 'TUNCELİ'), ('63', 'ŞANLIURFA'), ('64', 'UŞAK'), ('65', 'VAN'), ('66', 'YOZGAT'), ('67', 'ZONGULDAK'), ('68', 'AKSARAY'), ('69', 'BAYBURT'), ('70', 'KARAMAN'), ('71', 'KIRIKKALE'), ('72', 'BATMAN'), ('73', 'ŞIRNAK'), ('74', 'BARTIN'), ('75', 'ARDAHAN'), ('76', 'IĞDIR'), ('77', 'YALOVA'), ('78', 'KARABÜK'), ('79', 'KİLİS'), ('80', 'OSMANİYE'), ('81', 'DÜZCE')], default=('amasya', 'AMASYA'), max_length=30, verbose_name='Şehir:')),
                ('district', models.CharField(max_length=30, verbose_name='Mahalle / Semt:')),
                ('village', models.CharField(max_length=30, verbose_name='Köy / Kasaba:')),
                ('address', models.TextField(max_length=128, verbose_name='Tam Adres:')),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
