# Generated by Django 3.0.3 on 2020-03-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberAddressCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='turkey', max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberCreate',
            fields=[
                ('subscriber_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('public_ID', models.CharField(max_length=11, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email_address', models.EmailField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
    ]
