# Generated by Django 3.0.3 on 2020-04-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberaddresscreate',
            name='subscriber_ID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='abone.SubscriberCreate'),
        ),
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='address_owner',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscribercreate',
            name='subscriber_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
