# Generated by Django 3.0.3 on 2020-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberaddresscreate',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriberaddresscreate',
            name='date_of_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscribercreate',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribercreate',
            name='date_of_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
