# Generated by Django 3.0.3 on 2020-04-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0003_auto_20200402_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberaddresscreate',
            name='subscriber_ID',
        ),
        migrations.AddField(
            model_name='subscriberaddresscreate',
            name='subscriber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abone.SubscriberCreate'),
        ),
    ]
