# Generated by Django 3.0.3 on 2020-03-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0004_auto_20200326_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Şehir:'),
        ),
    ]
