# Generated by Django 3.0.3 on 2020-04-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0005_auto_20200402_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberaddresscreate',
            old_name='subscriber_ID',
            new_name='subscriber',
        ),
    ]
