# Generated by Django 3.0.3 on 2020-03-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0005_auto_20200326_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='country',
            field=models.CharField(default='Türkiye', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='district',
            field=models.CharField(default='Merkez', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='village',
            field=models.CharField(max_length=30),
        ),
    ]
