# Generated by Django 3.0.3 on 2020-03-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0006_auto_20200326_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='country',
            field=models.CharField(default='turkey', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='district',
            field=models.CharField(max_length=30),
        ),
    ]
