# Generated by Django 3.0.3 on 2020-04-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0006_auto_20200402_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberaddresscreate',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriberaddresscreate',
            name='subscriber_ID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='abone.SubscriberCreate'),
        ),
    ]
