# Generated by Django 3.0.3 on 2020-04-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0008_auto_20200402_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribercreate',
            old_name='subscriber_id',
            new_name='subscriber_ID',
        ),
        migrations.RemoveField(
            model_name='subscriberaddresscreate',
            name='subscriber',
        ),
    ]
