# Generated by Django 3.0.3 on 2020-04-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0009_auto_20200402_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberaddresscreate',
            name='address_owner',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
