# Generated by Django 3.0.3 on 2020-04-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0010_auto_20200402_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberaddresscreate',
            old_name='address_owner',
            new_name='address_owner_id',
        ),
    ]
