# Generated by Django 3.0.3 on 2020-04-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0011_auto_20200402_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribercreate',
            old_name='subscriber_ID',
            new_name='subscriber_id',
        ),
    ]
