# Generated by Django 3.0.3 on 2020-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0012_auto_20200402_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribercreate',
            name='subscriber_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
