# Generated by Django 3.0.3 on 2020-04-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0013_auto_20200403_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribercreate',
            name='seller_id',
            field=models.CharField(default=0, max_length=15, verbose_name='Bayi:'),
        ),
    ]
