# Generated by Django 3.0.3 on 2020-04-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abone', '0014_subscribercreate_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberaddresscreate',
            name='status',
            field=models.CharField(max_length=30, null=True, verbose_name='Durum:'),
        ),
        migrations.AddField(
            model_name='subscribercreate',
            name='status',
            field=models.CharField(max_length=30, null=True, verbose_name='Durum:'),
        ),
    ]
